# FakePluginsList 配置文件

# 触发命令列表 (不需要加/)
commands:
  - "plugins"
  - "bukkit:plugins"
  - "bukkit:pl"

# 是否显示加载失败的插件 (true/false)
show_failed_plugins: true

# 是否随机排序插件列表 (true/false)
random_order: true

# 显示消息 (%count% 会被替换为插件总数量, %plugins% 会被替换为插件列表)
# %success_count% 会被替换为成功加载的插件数量
# %failed_count% 会被替换为加载失败的插件数量
message: "&fPlugins (&f%count%&f): %plugins%"

# 显示的插件列表
# 成功加载的插件列表 (显示为绿色 &a)
success_plugins:
  - "Plugin1"
  - "Plugin2"

# 加载失败的插件列表 (显示为红色 &c)
failed_plugins:
  - "FailedPlugin1"
  - "FailedPlugin2"